import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './data/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface: '#141317',
        'surface-dim': '#141317',
        'surface-bright': '#3a383d',
        'surface-container-lowest': '#0f0d12',
        'surface-container-low': '#1c1b20',
        'surface-container': '#201f24',
        'surface-container-high': '#2b292e',
        'surface-container-highest': '#363439',
        'on-surface': '#e6e1e7',
        'on-surface-variant': '#cfc2d7',
        'inverse-surface': '#e6e1e7',
        'inverse-on-surface': '#312f35',
        outline: '#988ca0',
        'outline-variant': '#4c4354',
        'surface-tint': '#dcb8ff',
        primary: '#dcb8ff',
        'on-primary': '#480081',
        'primary-container': '#8a2be2',
        'on-primary-container': '#eed9ff',
        'inverse-primary': '#8422dc',
        'primary-fixed': '#efdbff',
        'primary-fixed-dim': '#dcb8ff',
        'on-primary-fixed': '#2c0051',
        'on-primary-fixed-variant': '#6700b5',
        secondary: '#bdf4ff',
        'on-secondary': '#00363d',
        'secondary-container': '#00e3fd',
        'on-secondary-container': '#00616d',
        'secondary-fixed': '#9cf0ff',
        'secondary-fixed-dim': '#00daf3',
        'on-secondary-fixed': '#001f24',
        'on-secondary-fixed-variant': '#004f58',
        tertiary: '#ecb2ff',
        'on-tertiary': '#520071',
        'tertiary-container': '#a100da',
        'on-tertiary-container': '#f8d6ff',
        'tertiary-fixed': '#f8d8ff',
        'tertiary-fixed-dim': '#ecb2ff',
        'on-tertiary-fixed': '#320047',
        'on-tertiary-fixed-variant': '#74009f',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        background: '#141317',
        'on-background': '#e6e1e7',
        'surface-variant': '#363439',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        sm: '0.25rem',
        md: '0.5rem',
        lg: '0.75rem',
        xl: '1rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'gutter-sm': '1rem',
        margin: '3rem',
      },
      fontFamily: {
        sans: ['Outfit', 'sans-serif'],
        playfair: ['"Playfair Display"', 'serif'],
        mono: ['"Space Mono"', 'monospace'],
      },
      fontSize: {
        'label-mono-sm': ['10px', { lineHeight: '14px', letterSpacing: '0.12em', fontWeight: '400' }],
        'label-mono': ['12px', { lineHeight: '16px', letterSpacing: '0.08em', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '300' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'title-md': ['16px', { lineHeight: '24px', letterSpacing: '0.02em', fontWeight: '600' }],
        'title-lg': ['20px', { lineHeight: '28px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '30px', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-xl-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-xl': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      animation: {
        'spin-slow': 'spin-slow 12s linear infinite',
        'spin-fast': 'spin-fast 4s linear infinite',
        vinyl: 'vinyl-spin 6s linear infinite',
        'ping-slow': 'ping-slow 2s cubic-bezier(0, 0, 0.2, 1) infinite',
      },
      keyframes: {
        'spin-slow': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'spin-fast': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'vinyl-spin': {
          from: { transform: 'rotate(0deg)' },
          to: { transform: 'rotate(360deg)' },
        },
        'ping-slow': {
          '75%, 100%': { transform: 'scale(2)', opacity: '0' },
        },
      },
      backgroundImage: {
        'vinyl-grooves': 'repeating-radial-gradient(circle, transparent 0, transparent 2px, rgba(255,255,255,0.03) 3px, rgba(255,255,255,0.01) 4px)',
      },
    },
  },
  plugins: [],
};

export default config;
